# .github/workflows/app.yaml
name: Test API
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:

      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install -r requirements.txt
      - name: Run test
        run: |
          pytest --alluredir=allure-results 

     

      - name: Add allure information
        working-directory: allure-results
        if: always()
        run: |
          echo GIT_BRANCH=${{ github.head_ref || github.ref_name }}  >> environment.properties
          echo GIT_COMMIT_ID=${{ github.sha }} >> environment.properties
          echo GIT_COMMIT_MESSAGE=$(git show -s --format=%s HEAD) >> environment.properties
          echo GIT_COMMIT_AUTHOR_NAME=$(git show -s --format='%ae' HEAD) >> environment.properties
          echo GIT_COMMIT_TIME=$(git show -s --format=%ci HEAD) >> environment.properties
          echo CHROME_VERSION=$(google-chrome --product-version) >> environment.properties
      - name: Allure results
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: gh-pages
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Generate report URL
        if: always()
        run: |
          echo "REPORT_URL=https:/repo$GITHUB_RUN_NUMBER/" >> $GITHUB_ENV
